### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by refractionhq** [javaguirre/comment#10]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Aria\AppData\Local\atom\app-0.188.0\resources\app\src\atom.js:54:11)
Object.activate (C:\Users\Aria\.atom\packages\comment\lib\comment.js:8:13)
```

**Comment by supergithubo** [comment]
Can be fixed with pull request #12
