### ISSUE TITLE
No available version compatible with the installed Atom version: 1.7.4

### ISSUE THREAD

**Issue by danielbayley** [javaguirre/comment#23]
This package won't install due to the above error 😢

**Comment by holaneph** [comment]
bump.

**Comment by javaguirre** [comment]
This should be fixed in the last version, I will add It today (#24).

**Comment by javaguirre** [comment]
Added, please let me know if you have any problems with It.

**Comment by holaneph** [comment]
Works like a charm, Thanks man!
