### ISSUE TITLE
Comment position

### ISSUE THREAD

**Issue by danielbayley** [javaguirre/comment#25]
Block comments
-----------------
Match indentation of selected text, for example with CoffeeScript:
~~~ coffee
··function: (var) ->
····if var?
······console.log var
··###
··function: (var) ->
····if var?
······console.log var
··###
~~~
rather than what it currently does:
~~~ coffee
###
··function: (var) ->
····if var?
······console.log var
###
~~~
Single line comments
---------------------
Same thing here:
~~~ coffee
··#·console.log "something"
~~~
rather than what it currently does:
~~~ coffee
#···console.log "something"
~~~
Also, a setting to configure space between comment and _commented_ line would be handy:
~~~ coffee
··#console.log "something" # atom.config.get 'comment.spaceBetween' # none
··#·console.log "something" # atom.config.get 'comment.spaceBetween' # space
~~~

**Comment by javaguirre** [comment]
Yes, I agree with you on everything, I'll fix it. :-)
