### ISSUE TITLE
Message error when trying to use it in .tex file

### ISSUE THREAD

**Issue by simas0** [javaguirre/comment#38]
Got the message below when tried to use the short cut for commenting.

> Uncaught TypeError: Cannot read property 'length' of undefined
> /home/simas/.atom/packages/comment/lib/comment-utils.js:220
> Show Stack Trace
> The error was thrown from the comment package. You can help by creating an issue. Please explain what actions triggered this error.
> Create issue on the comment package

**Comment by javaguirre** [comment]
We don't support tex files, but it shouldn't be a problem, I'll fix ir soon enough.

Thank you!
