### ISSUE TITLE
Shift + M key shortcut

### ISSUE THREAD

**Issue by Positive07** [javaguirre/comment#48]
For some reason the default keyboard shortcut for Toggle Comment is `Shift+M` which when used in Atom results in an `M` and not a comment. I tried `Alt+Shift+M` and `Ctrl+Shift+M` but neither worked.

You can see what I mean in the following images which compare the Command Palette to Comment:
![captura de pantalla 2017-05-08 13 56 37](https://cloud.githubusercontent.com/assets/1095969/25815365/7d2e07b2-33f6-11e7-8e32-3a6baedd299c.png)

The system is Windows 10 x64 with ES (Spanish) keyboard layout. I think the issue appeared back in Atom 1.15 (if not before haven't actually checked), I'm now running on the beta 5 of 1.17

https://discuss.atom.io/t/cmd-key-on-linux/9056/4

**Comment by javaguirre** [comment]
Thank you for reporting and for the PR! 💯
