### ISSUE TITLE
Support for xml.

### ISSUE THREAD

**Issue by manonthegithub** [javaguirre/comment#56]
I've installed plugin and tried to comment xml file. So it didn't work out of the box, and I removed plugin.

**Comment by javaguirre** [comment]
Hi! thank you for your comment, I don't use Atom anymore, but I'm open for PRs, so if you want to prepare this support, you're more than welcome!

**Comment by manonthegithub** [comment]
Cool, I just did it). 
If it's not a secret what do use instead of Atom )?

**Comment by javaguirre** [comment]
Well, I was using Emacs, but then a friend of mine showed me Visual Studio Code, so I'm using that. What I value the most is the vi mode, and they've improved it a lot, also the version control capabilites inside the editor are nice, among other things. :-)

**Comment by javaguirre** [comment]
Thank you for the PR! :-)

**Comment by javaguirre** [comment]
Closing this issue since you solved it on #57

**Comment by manonthegithub** [comment]
Please add one more commit from #58 as I haven't added xml to single line exclusions

**Comment by manonthegithub** [comment]
And thanks for you reply about the editor. I am in constant search of the best one for Mac).
