### ISSUE TITLE
I think we don't have a need to use this package.

### ISSUE THREAD

**Issue by muaadhsherif** [javaguirre/comment#59]
Thanks for who did this package, but I think we don't have a need to use this package as atom does this without packages. Just type:
**ctrl-/**         : to make the hole line as a comment.
**ctrl-shift-/** : to comment the selected text and if there is no-selected text it gives you an empty comment.

**Comment by javaguirre** [comment]
OK, I'll mark it as deprecated, I don't use Atom anymore.

**Comment by javaguirre** [comment]
Done.

**Comment by muaadhsherif** [comment]
Thank you for your respect.
But Can you tell me which editor you use and why?
Are you using vim now ?
I want to learn from your experience.

**Comment by javaguirre** [comment]
I’ve used many different since i learnt vim. Now I'm using visual studio code. It has a decent vi mode and a more comfortable approach to debugging, version control... :-)

**Comment by muaadhsherif** [comment]
But what are the advantages of VSC over Atom ?
So you recommend me to leave Atom ?

**Comment by javaguirre** [comment]
It's ok, I can't maintain it anyway. Thank you for the issue!

I like VS Code, I find it more mature than Atom, bu I haven't used it for a while so who knows. You can give it a try for a while, see for yourself, it's always nice to test new stuff, maybe there is something you might learn from that experience.
